---
- name: install and start apache on ec2 insance
  hosts: webserver
  become: yes

  tasks:
    - name: install httpd service
      yum:
        pkg: httpd
        state: installed

    - name: uploading default index.html for host 
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html

    - name: start httpd service
      service:
        name: httpd
        state: started
