---
- name: terminating EC2, Load Balancer, Target group
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: Get instance ID of EC2.
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Owner": "CICD"
          instance-state-name: running

      register: ec2_id

    - name: Build a list of all the EC2 instancce id.
      set_fact:
        ec2_instance_id: "{{ ec2_instance_id }} + [ '{{ item.instance_id }}' ]"
      with_items: "{{ ec2_id.instances }}"
    - debug: var=ec2_instance_id
    - name: terminate ec2
      ec2:
        instance_ids: "{{ ec2_instance_id }}"
        region: "{{ region }}"
        state: absent
        wait: True
      ignore_errors: true
      register: ec2
    - debug:
        msg: "{{ ec2 }}"
        
    
    - name: delete EC2_ELB
      elb_application_lb:
        name: "{{ elb_name }}"
        region: "{{ region }}"
        state: absent

    - name: deleting target group
      pause:
        seconds: 120
    - name: deledting target group
      elb_target_group:
        name: "{{ target_group_name_vote }}"
        region: "{{ region }}"
        state: absent
    - name: deledting target group
      elb_target_group:
        name: "{{ target_group_name_result }}"
        region: "{{ region }}"
        state: absent

    
    - name: delete rds instance
      rds:
        command: delete
        instance_name: "{{ db_name }}"
        region: "{{ region }}"
      register: rds_delete

    - rds_subnet_group:
        state: absent
        name: CICD-subnet_group
        region: "{{ region }}"
      register: subnet_group_delete
 
    - elasticache:
        name: "cicd-redis-new"
        state: absent 
        region: "{{ region }}"
 
